### ISSUE TITLE
cleanups for 1.0.8

### ISSUE THREAD

**Issue by peterdd** [cmanley/p5-PHP-Functions-Password#1]
Thanks for the quick implementation.

Some things need a cleanup:

* Update Changes (ups, I see you are working on it, but we have year 2020 ;-) )
* DESCRIPTION on metacpan.org is still the old
* `man PHP::Functions::Password` shows the old POD, but 
  `perl -e 'use PHP::Functions::Password; print $PHP::Functions::Password::VERSION;'` says 1.0.8
* The dependancy graph linked on metacpan.org does not show the argon2 dependancy, but the reverse graph when being in Crypt::Argon2 shows the usage by PHP::Functions::Password
* The 'How to Contribute' https://metacpan.org/contributing-to/PHP-Functions-Password shows the default _Oops! No Contributing guidelines for PHP-Functions-Password found_

**Comment by cmanley** [comment]
I'll clean those things up in the coming days. 
metacpan.org always lags a little with updates.
Crypt::Argon2 is optional. The make file generates a warning if it's not present, but allows you to install the module anyway. I'm not sure how that dependency graph stuff works.

**Comment by peterdd** [comment]
The dependancy graph is now showing Crypt-Argon2 too.
I tried 1.0.9 installing on Opensuse 15.1 and Debian 10 with `cpanm PHP::Functions:Password` and it installed the missing Crypt::Argon2 too (which is fine/good for me)

**Comment by cmanley** [comment]
v1.10 will show up in metacpan soon.
